### ISSUE TITLE
GTR2e - 01-WF-MD225-V3 - missing xdrip data

### ISSUE THREAD

**Issue by twinko** [twinko/xdrip-watchface-collection#1]
History:
https://github.com/twinko/GTR-2-WF-Xdrip-guide/issues/9

##############
**abeldsb:**

@twinko
Hello, I have the gtr 2e watch, I follow the steps to download the files in the xdrip folder and the dial does not load.
Thanks in advance.
All the best
![128607250-03ffb120-46f1-4787-814f-4db636160737](https://user-images.githubusercontent.com/11973158/128668919-36d57d1a-006d-4303-93d1-02414c350962.gif)

#################################
**twinko**

@abeldsb hmmmm, what files are in your xdrip folder? looks like its not loading the my_image.png
The files are tested by bigdigital, so i guess it should work.

Followig files need to be in the xdrip folder:

config.json
my_image.png
my_watchface.bin

The are found here:
https://github.com/twinko/GTR-2-WF-Xdrip-guide/tree/main/01-WF-MD225-Version3-xdrip-ready
@abeldsb
abeldsb commented 17 hours ago

###############################################
**abeldsb**

@twinko
Hello, thanks for answering. Those three files are the ones I put in the xdrip folder and what happens when the sphere updates the files from the default sphere return, I delete them but they come back again.
Thanks again.

**Comment by twinko** [comment]
@abeldsb Please make a screenshot of you xdrip folder. Moreover, did you enabled custom watchface n xdrip settings?

**Comment by abeldsb** [comment]
@twinko Hello, thanks for responding and taking the time.
I am attaching screenshots.
The first is from the xdrip configuration.
The second is when I copy the files into the xdrip folder.
The third is when I update the dial so that it loads on the watch and the other files appear.

Thanks for your time.

![Screenshot_20210809-123757_xDrip+](https://user-images.githubusercontent.com/70631814/128696141-150c2adb-9e43-4aae-92db-d3e7601fd35a.jpg)
![20210809_124639](https://user-images.githubusercontent.com/70631814/128696170-431db3df-458e-4455-ac61-92cde4096f67.jpg)
![20210809_124703](https://user-images.githubusercontent.com/70631814/128696205-de39fd81-08c8-41f1-a93e-170d7a2559bd.jpg)

**Comment by twinko** [comment]
@abeldsb What happens when you copy over the files , disconnect the phone from the pc and reconnect it right away? Are the files gone?

**Comment by abeldsb** [comment]
@twinko  No, I leave the phone connected to the computer

**Comment by abeldsb** [comment]
@twinko No, I leave the phone connected to the computer and when I load the face on the watch the default xdrip face appears and the previous files appear.

**Comment by twinko** [comment]
@abeldsb


Thats what im saying, try the following and let me know what you see in the folder:

1. connect to the pc
2. put the files of the new Watchface in the xdrip folder
3. disconnect phone from the PC
4. Connect the phone agian to the pc (without wathfache upload to the watch)
5. Check if something changed. --> Tell me the result, what file are in the folder

**Comment by abeldsb** [comment]
@twinko Hello, I have not been able to check it before.
I have followed your instructions, I load the files, I disconnect the phone from the computer, I connect it and they are still there, but the problem is when the sphere is loaded again that loads the one that is predetermined and I check and the previous files are back again , I delete them again, but when I update the sphere they come back again.
I appreciate the time you spend on it.
Thanks.

**Comment by twinko** [comment]
Hi @abeldsb I'm sorry but i don't know why its not working!  Sadly i have problems receiving the watch, so i cant test it by myself. But Artem tried it and it worked for him. If someone can reproduce the issue or i receive my watch, I'll have abother look into that.

**Comment by abeldsb** [comment]
@twinko Hi, okay. Thank you for your support and especially for your work. I will keep trying and if I make any progress I will tell you. Thanks for everything. Greetings.
