### ISSUE TITLE
image doubling  

### ISSUE THREAD

**Issue by Alevtinaalevtina** [twinko/xdrip-watchface-collection#3]
Hello! Can you help me, please? I like your watchface, but I have such problems - image  doubling. Also I can't understand why I can see points with carbs and insulin doses, and graphics of the activity of insulin. should xdrip give it for watchface? 
![16375825001373392939846337294406](https://user-images.githubusercontent.com/83495518/142858492-09d34ef7-f778-41d8-b72d-41d2a99b763f.jpg)

**Comment by twinko** [comment]
Hi @Alevtinaalevtina ,

so you are talkingabout WF 15. This WF was created by @mavricaaa
Im having some problems understanding your questions.
1. what do you mean by image doubling?
2. the graph comes directly from the xdrip app, so if the data is shown in the xdrip app it should be shown o the watch as well.
Regards

**Comment by Alevtinaalevtina** [comment]
Ohh, thank you, I add @mavricaaa here too, sorry.
This watchface shows last carbs, last insulin dose and glucose change from the last checking.
Insulin dose and carbs is superimposed on each other in watchface and I can't read it

**Comment by twinko** [comment]
ahh now i understand. The xdrip data is on top of the graph and its hard to read both, the grah and the numbers.
This is an issue of the watchface. @mavricaaa would have to reorganize the watchface.

If you dont want to wait (assuming that he implements it) you can change it by yourself. Read into the following guide: 
https://github.com/twinko/GTR-2-WF-Xdrip-guide

you can tr to tinker around with the config.json but i think you would need to change the watchface layout to have a realy clean look.

**Comment by Alevtinaalevtina** [comment]
Thank you for advice. I will try to do that myself. That will be my first such work. I hope, I can  :)

**Comment by mavricaaa** [comment]
@Alevtinaalevtina hii:) oh, as I can see the coordinates are right, there is no overlay problem, but you have and additional activated graph on your xdrip-the green one, which is maybe a carbs graph or a predictive graph? I am not using that one so that is why the coordinates were configured without that setting. If you could help me please which one is that so I can check it? :)

**Comment by Alevtinaalevtina** [comment]
> @Alevtinaalevtina hii:) oh, as I can see the coordinates are right, there is no overlay problem, but you have and additional activated graph on your xdrip-the green one, which is maybe a carbs graph or a predictive graph? I am not using that one so that is why the coordinates were configured without that setting. If you could help me please which one is that so I can check it? :)

Hello) of course I help you, this is line of bolus insulin. It shows in setting color scheme. I haven't found a way to turn it off now.

**Comment by Alevtinaalevtina** [comment]
@mavricaaa and i don't see last dose of insulin on your watchface, but I have it. May be is problem there? There is only carbs and delta of glucose on your watchface

**Comment by mavricaaa** [comment]
![IMG_20211122_192604 (1) (4)](https://user-images.githubusercontent.com/93980950/142916286-53964e52-97da-48a3-9b3d-dacdc3fcd9e8.jpg)
@Alevtinaalevtina Hi! I added the insulin on board now, it is visible and deactived the bolus graph on WF (Settings-Smart Watch Features-MiBand-General Settings- remove the tick from _Show bolus_ box). The new config file is available temporarily at the following link https://easyupload.io/msbc4t so  just replace the config file in xdrip folder that you originally downloaded for the WF with the new one. :)

@twinko Hi again:) It looks like i cannot add files to the repo, so please replace the new config.json file in WF if possible I have fixed the coordinates now. Or if there is other way I can do it directly instead of bothering you every time with a new upload please let me know :)

**Comment by Alevtinaalevtina** [comment]
@mavricaaa thank you so much! :) now this is a such convenient watchface

**Comment by twinko** [comment]
@mavricaaa @Alevtinaalevtina 
awesome you worked that out. i already updatet the config.json, so the next people will have the right one :)
